services:
  postgres:
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_DB: dobook_db
      POSTGRES_PASSWORD: vlad
      POSTGRES_USER: vlad
    ports:
      - '5432:5432'
    networks:
      - dobook_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    networks:
      - dobook_net

networks:
  dobook_net:

volumes:
  postgres_data:
